global:
  # the entity ID used for all tests (unless overridden later)
  entity_id: test_val
  # certificate and key filename (relative to the config file)
  cert: test.crt
  # certificate and key filename (relative to the config file)
  key: test.key
  # static token (optional)
  #token: mektmiasdigoat

http:
  # perform certificate validation (default True)
  verify: True
  # HTTP proxies (optional)
  #proxies:
  #  https: http://127.0.0.1:3128/

macros:
  # known good ticket ID (for validation/inspection testing)
  TICKET_ID: 58221f2f13fc33000713b79c

test:
  authentication:
    endpoint: https://test1.mobileticket.se/api/v1
  device:
    endpoint: https://test1.mobileticket.se/api/v1
    entity_id: test_val
  product:
    endpoint: https://test1.mobileticket.se/api/v1
    # products to acquire manifests for
    manifests: "bobby_client/testdata/product_manifests.json"
    # filters to test
    filters: "bobby_client/testdata/product_filters.json"
  ticket:
    endpoint: https://test1.mobileticket.se/api/v1
  validation:
    endpoint: https://test1.mobileticket.se/api/v1
    # list of known good events to submit
    good_events: "bobby_client/testdata/ticket_events_good.json"
    # list of known bad events to submit
    bad_events: "bobby_client/testdata/ticket_events_bad.json"
    tickle_macro_serials: [ 1, 2 ]
  inspection:
    endpoint: https://test1.mobileticket.se/api/v1
    # list of known good events to submit
    good_events: "bobby_client/testdata/ticket_events_good.json"
    # list of known bad events to submit
    bad_events: "bobby_client/testdata/ticket_events_bad.json"
